kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: aap-kafka-manager
  namespace: aap
  labels:
    team: aap
spec:
  image: docker.pkg.github.com/navikt/kafka-manager/kafka-manager:2.2022.02.14_08.11-14fd30c0514f # See https://github.com/navikt/kafka-manager/packages
  port: 8080
  webproxy: true
  ingresses:
    - https://aap-kafka-manager.dev.intern.nav.no
  prometheus:
    enabled: true
    path: /internal/prometheus
  readiness:
    path: /internal/health/readiness
    initialDelay: 20
  liveness:
    path: /internal/health/liveness
    initialDelay: 20
  replicas:
    min: 1
    max: 1  # 1 instance is required since in-memory session management is used
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "1"
      memory: 1024Mi
    requests:
      cpu: 250m
      memory: 512Mi
  azure: # Required
    application:
      enabled: true
      tenant: nav.no
      claims:
        groups:
          - id: 66f2ac6d-9ca0-4c1d-962b-19a9fb98a8f3
  kafka: # Optional. Required for Aiven
    pool: nav-dev
  env:
    - name: APP_CONFIG_JSON # Required
      value: >
          {
            "topics": [
              {
                "name": "aap.sokere.v1",
                "location": "AIVEN",
                "keyDeserializerType": "STRING",
                "valueDeserializerType": "AVRO"
              },
              {
                "name": "aap.inntekter.v1",
                "location": "AIVEN",
                "keyDeserializerType": "STRING",
                "valueDeserializerType": "AVRO"
              },
              {
                "name": "aap.manuell.v1",
                "location": "AIVEN",
                "keyDeserializerType": "STRING",
                "valueDeserializerType": "AVRO"
              },
              {
                "name": "aap.medlem.v1",
                "location": "AIVEN",
                "keyDeserializerType": "STRING",
                "valueDeserializerType": "AVRO"
              },
            ]
          }
